<?php
/**
 * [execute=<name>]
 * include some external PHP script and display its output
 *
 * The referenced script has to be located inside the YACS installation
 * directory. Leading '/', './' and '../' sequences are stripped from the
 * provided path, so the inclusion cannot escape the installation tree.
 *
 * SECURITY WARNING: this code executes an arbitrary PHP script straight
 * from page content, which makes it a content-driven code execution
 * vector. This is why it is parked in codes/unused/ and disabled by
 * default. To enable it on your server, move this file to codes/ and
 * delete codes/patterns.auto.php to rebuild the patterns cache.
 *
 * @author Bernard Paques (rendering)
 * @reference
 * @license http://www.gnu.org/copyleft/lesser.txt GNU Lesser General Public License
 */

class Code_execute extends Code {

    // [execute=<name>]
    var $patterns = array('/\[execute=([^\]]+?)\]/is');

    /**
     * include one PHP script of this installation
     *
     * @param array with the name of the script to include
     * @return string the text generated during the inclusion
    **/
    public function render($matches) {
        global $context;

        $name = isset($matches[0]) ? trim($matches[0]) : '';

        // check path to the file
        while($name !== '') {

            // remove leading /
            if($name[0] == '/') {
                $name = substr($name, 1);
                continue;
            }

            // avoid reference to current directory
            if(!strncmp($name, './', 2)) {
                $name = substr($name, 2);
                continue;
            }

            // can't go outside this instance of yacs
            if(!strncmp($name, '../', 3)) {
                $name = substr($name, 3);
                continue;
            }

            break;
        }

        // nothing to include
        if($name === '' || !is_readable($context['path_to_root'].$name))
            return '';

        // capture the output of the next script in memory
        ob_start();

        // load this file, somewhere below the installation directory
        include $context['path_to_root'].$name;

        // retrieve all text generated by the script
        $output = ob_get_contents();
        ob_end_clean();

        // display the text where the script was included
        return $output;
    }
}
